collections:
  - name: pages
    label: Website Pages
    type: folder
    path: /
    format: html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Main Content
        type: rich-text